spring:
  main:
    allow-circular-references: true
  redis:
    host: redis-15544.c232.us-east-1-2.ec2.redns.redis-cloud.com
    port: 15544
    ssl: true
    password: nQ1nYgckFTPLm7wsbeIUNg7HGGWHDKUK
  data:
    mongodb:
      uri: mongodb+srv://appubanka:appu1996@newscluster.vxc6u.mongodb.net/?retryWrites=true&w=majority&appName=NewsCluster
      database: newsdb
      auto-index-creation: true

  mail:
    host: smtp.gmail.com
    port: 587
    username: appu.banka@gmail.com
    password: xxxx xxxx xxxx xxxxx
    properties:
      mail:
        smtp:
          auth: true
          starttls:
            enable: true

server:
  port: 8081